FROM node:12-alpine AS build

ARG BUILDARG

USER node
WORKDIR /home/node

COPY package*.json ./

RUN npm install

COPY . .

RUN $(npm bin)/ng build $BUILDARG --output-path=dist

FROM nginx:1.19-alpine
COPY ./configs/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /home/node/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]